twig:
    file_name_pattern: '*.twig'
    globals:
        social_whatsapp_url: '%social_whatsapp_url%'
        social_snapchat_url: '%social_snapchat_url%'

when@test:
    twig:
        strict_variables: true
